const productStats: ProductStatItem[] = [
    {
      id: "credit-cards",
      title: "Credit Cards",
      value: "42%",
      trend: { direction: "up", change: "+8% from last month", color: "text-red-500" },
      topIssue: "Transaction disputes",
      IconComponent: FileText,
      iconContainerClass: "bg-red-100",
      iconClass: "text-red-500",
      headerClass: "bg-gradient-to-r from-red-50 to-red-100/50 dark:from-red-900/20 dark:to-red-800/10",
    },
    {
      id: "personal-loans",
      title: "Personal Loans",
      value: "35%",
      trend: { direction: "up", change: "+5% from last month", color: "text-red-500" },
      topIssue: "Application delays",
      IconComponent: Package,
      iconContainerClass: "bg-amber-100",
      iconClass: "text-amber-500",
      headerClass: "bg-gradient-to-r from-amber-50 to-amber-100/50 dark:from-amber-900/20 dark:to-amber-800/10",
    {
      id: "savings-accounts",
      title: "Savings Accounts",
      value: "28%",
      trend: { direction: "down", change: "-3% from last month", color: "text-green-500" },
      topIssue: "Interest rate concerns",
      IconComponent: BarChart3,
      iconContainerClass: "bg-blue-100",
      iconClass: "text-blue-500",
      headerClass: "bg-gradient-to-r from-blue-50 to-blue-100/50 dark:from-blue-900/20 dark:to-blue-800/10",
    },
    {
      id: "mortgages",
      title: "Mortgages",
      value: "22%",
      trend: { direction: "up", change: "+2% from last month", color: "text-red-500" },
      topIssue: "Refinancing questions",
      IconComponent: Headphones,
      iconContainerClass: "bg-green-100",
      iconClass: "text-green-500",
      headerClass: "bg-gradient-to-r from-green-50 to-green-100/50 dark:from-green-900/20 dark:to-green-800/10",
    },
    {
      id: "investment-products",
      title: "Investment Products",
      value: "18%",
      trend: { direction: "up", change: "+4% from last month", color: "text-red-500" },
      topIssue: "Performance concerns",
      IconComponent: Package,
      iconContainerClass: "bg-purple-100",
      iconClass: "text-purple-500",
      headerClass: "bg-gradient-to-r from-purple-50 to-purple-100/50 dark:from-purple-900/20 dark:to-purple-800/10",
    },
  ]