version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../infra/Dockerfile  # Dockerfile for Next.js in infra
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile  # You’ll put a separate Dockerfile inside backend/
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../backend:/app
